In [71]:
import pandas as pd
di=[{"name":"Alice","age":25,"city":"New York"},
    {"name":"Bob","age":30,"city":"Los Angeles"}]
df=pd.DataFrame(di)
print(df)

    name  age         city
0  Alice   25     New York
1    Bob   30  Los Angeles

In [72]:
df.loc[0,"age"]=26
df.loc[1,"city"]="San Francisco"

df1=df.loc['age':'city']
df1

Empty DataFrame
Columns: [name, age, city]
Index: []

In [73]:
df.loc[:,'age':'city']

   age           city
0   26       New York
1   30  San Francisco

df.iloc[:2]

In [74]:
df.iloc[0:2]

    name  age           city
0  Alice   26       New York
1    Bob   30  San Francisco

In [75]:
df=pd.read_csv("matches.csv")
df.head()
df.isnull().sum()
# df.isnull().any()
# df.dtypes
# df.describe()
# df.fillna('Nan',inplace=True)
# df.head()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

Fill Missing Values for Float (Numerical Columns)

Usually we fill with:

✅ Mean
Fill with Mean Used when data is normally distributed

✅ Median
Fill with Median (Better if outliers present)

✅ 0 (sometimes)

2️⃣ Fill Missing Values for String (Categorical Columns)

Usually we fill with:

✅ Mode (most frequent value)

✅ "Unknown"

✅ "Missing"

Numerical → Fill with mean / median

Categorical → Fill with mode

Use fillna() function

df

In [76]:
df.city.fillna('Unknown',inplace=True)
df.rename(columns={'city':'location'},inplace=True)
df.head()

C:\Users\Hp\AppData\Local\Temp\ipykernel_1108\3848616642.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.city.fillna('Unknown',inplace=True)

,id,season,location,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [77]:
df['location'].value_counts()

location
Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Centurion         12
Ahmedabad         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Cape Town          7
Port Elizabeth     7
Cuttack            7
Ranchi             7
Abu Dhabi          7
Raipur             6
Sharjah            6
Indore             5
Kochi              5
Kanpur             4
East London        3
Kimberley          3
Nagpur             3
Bloemfontein       2
Name: count, dtype: int64

In [78]:
df

,id,season,location,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [79]:
df['location'].value_counts()

location
Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Centurion         12
Ahmedabad         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Cape Town          7
Port Elizabeth     7
Cuttack            7
Ranchi             7
Abu Dhabi          7
Raipur             6
Sharjah            6
Indore             5
Kochi              5
Kanpur             4
East London        3
Kimberley          3
Nagpur             3
Bloemfontein       2
Name: count, dtype: int64

In [80]:
df.head()
df['new_val']=df['win_by_runs'].apply(lambda x: 'High' if x>10 else 'Low')
df.head()

,id,season,location,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,new_val
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,High
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,Low
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,Low
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,Low
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,High

In [81]:
df=df.groupby('location').agg({'win_by_runs':'mean'})

In [82]:
df=df.groupby('location')['win_by_runs'].agg(['mean','sum','count'])
df

                     mean        sum  count
location
Abu Dhabi       22.428571  22.428571      1
Ahmedabad       15.000000  15.000000      1
Bangalore       19.136364  19.136364      1
Bloemfontein     7.000000   7.000000      1
Cape Town       20.714286  20.714286      1
Centurion        6.750000   6.750000      1
Chandigarh      12.521739  12.521739      1
Chennai         14.895833  14.895833      1
Cuttack         10.428571  10.428571      1
Delhi           14.600000  14.600000      1
Dharamsala      31.000000  31.000000      1
Durban          10.600000  10.600000      1
East London     29.000000  29.000000      1
Hyderabad        9.918367   9.918367      1
Indore           0.000000   0.000000      1
Jaipur          13.939394  13.939394      1
Johannesburg     3.125000   3.125000      1
Kanpur           0.000000   0.000000      1
Kimberley       17.666667  17.666667      1
Kochi           22.000000  22.000000      1
Kolkata          9.622951   9.622951      1
Mumbai          12.964706  12.964706      1
Nagpur           5.000000   5.000000      1
Port Elizabeth  28.571429  28.571429      1
Pune            17.031250  17.031250      1
Raipur           3.500000   3.500000      1
Rajkot           7.000000   7.000000      1
Ranchi           5.857143   5.857143      1
Sharjah         12.333333  12.333333      1
Visakhapatnam   25.636364  25.636364      1

In [83]:
import pandas as pd
df1=pd.DataFrame({'Key':['1','2','3'],'value':['a','b','c']})
df2=pd.DataFrame({'Key':['1','4','5'],'value':['a','b','c']})
df3=pd.merge(df1,df2,on='Key',how='inner')
df3

  Key value_x value_y
0   1       a       a

In [84]:
import numpy as np
a = np.array([[1,2,3,4],
              [2,3,4,5]])
a.shape
a.reshape(1,8)
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [85]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])